// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQLJB8P_535p6IKlrIkUULmCHLlzNBGBo',
    appId: '1:1080448815688:web:1e2e1ea4ffc521122bbe7d',
    messagingSenderId: '1080448815688',
    projectId: 'kisahnusantaraapp',
    authDomain: 'kisahnusantaraapp.firebaseapp.com',
    storageBucket: 'kisahnusantaraapp.firebasestorage.app',
    measurementId: 'G-NKQ8QQDEP5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmM0rujT4QefZmm9X-PkYQflpbE-vkGhw',
    appId: '1:1080448815688:android:4f6269fb1e49bc212bbe7d',
    messagingSenderId: '1080448815688',
    projectId: 'kisahnusantaraapp',
    storageBucket: 'kisahnusantaraapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKaCF0U2kyF-s4Y-FkjYbREkrZUZC9Soo',
    appId: '1:1080448815688:ios:39af88087dee53fe2bbe7d',
    messagingSenderId: '1080448815688',
    projectId: 'kisahnusantaraapp',
    storageBucket: 'kisahnusantaraapp.firebasestorage.app',
    iosBundleId: 'com.example.kisahNusantaraApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKaCF0U2kyF-s4Y-FkjYbREkrZUZC9Soo',
    appId: '1:1080448815688:ios:39af88087dee53fe2bbe7d',
    messagingSenderId: '1080448815688',
    projectId: 'kisahnusantaraapp',
    storageBucket: 'kisahnusantaraapp.firebasestorage.app',
    iosBundleId: 'com.example.kisahNusantaraApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQLJB8P_535p6IKlrIkUULmCHLlzNBGBo',
    appId: '1:1080448815688:web:28d29dd81df7e2752bbe7d',
    messagingSenderId: '1080448815688',
    projectId: 'kisahnusantaraapp',
    authDomain: 'kisahnusantaraapp.firebaseapp.com',
    storageBucket: 'kisahnusantaraapp.firebasestorage.app',
    measurementId: 'G-WT2HEGTPLQ',
  );
}
